name: Build APK

on:
  push:
    branches:
      - master # Adjust to your default branch name
  pull_request:

jobs:
  build-apk:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.2'
          channel: stable

      # Recreate the .env file from secrets
      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      # Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Build the APK
      - name: Build APK
        run: flutter build apk --release

      # Upload APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
