name: Build Flutter App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out the code
      uses: actions/checkout@v2

    # Step 2: Set up Java 17
    - name: Set up Java 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Set up Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'  # Adjust to the desired version of Flutter

    # Step 4: Install dependencies
    - name: Install dependencies
      run: flutter pub get

    # Step 5: Build the Flutter project (Release)
    - name: Build Flutter Release APK
      run: flutter build apk --release

    # Optional: If you're targeting other platforms, add them here (e.g., iOS, Web, macOS, etc.)
    # - name: Build Flutter Web
    #   run: flutter build web

    # Optional: Upload artifacts if needed
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: flutter-apk
        path: build/app/outputs/flutter-apk/app-release.apk
